name: hh_express
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  very_good_infinite_list: ^0.7.0
  flutter_native_splash: ^2.3.0
  shimmer: ^3.0.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.8.1
  go_router: ^7.0.2
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  extended_wrap: ^0.1.5
  intl: ^0.18.0
  # flutter_svg: ^2.0.6
  flutter_svg_provider: ^1.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/navBarIcons/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
